Create subway functions
kamatozzzik/Subway pull request #17
Opened 2019-03-20 12:23 UTC by kamatozzzik

2019-03-20 13:06 UTC, AndreiShenets requested changes

2019-03-20 13:06 UTC, AndreiShenets commented on src/js/startApp.js
> +import { createSubway } from './subway func'
Do not use spaces in file names

2019-03-20 13:06 UTC, AndreiShenets commented on src/js/startApp.js
> +    subwayData = parser.handleToArray(subwayData);
One method parse is expected. Should return complitely built model

2019-03-20 13:06 UTC, AndreiShenets commented on src/js/subway func.js
> +import { Station } from './Station';
These functions should belong to Parser why did you extract them to separate file?

2019-03-20 13:07 UTC, AndreiShenets requested changes

2019-03-20 13:07 UTC, AndreiShenets commented on src/js/startApp.js
> +const lsKeys = {
it is worth to create separate constant for this. also it is worth to name it with full name localStorageKeys

2019-03-21 08:10 UTC, kamatozzzik commented
all fixed

2019-03-21 08:44 UTC, AndreiShenets requested changes

2019-03-21 08:44 UTC, AndreiShenets commented on package.json
> +  "main": "webpack.config.js",
Why this file is main? It is a start point of your application. Usually index.html or index.js

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +export function parseToSubway(data) {
why name is parseToSubway? parseSubwayData or just parse is ok. parseToSubway isn't like English phrase

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +
unnecessary line

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    array = Array.from(array);
Why do you do this?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +function handleToArray(data) {
handleToArray isn't like English phrase: convertToArray is more like what you want

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    array = array.map(name => {
arrow functions support syntax like .map(name => name.trim())

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +function handleToSubway(data) {
handleToSubway isn't like English phrase. buildSubwayModel is more like what you want

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    let stationNames = [], names = [], lineNames = [];
what does names array contain? it is hard to understand from the name

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +        if (!name || data.lastIndexOf(name) === data.length - 1) {
you introduce additonal algorithmic complexity using lastIndexOf. The first one you can use simple for and have index and determine index of current element without lastIndexOf. The second one forEach() has the second parameter index.
Also you call it twice!

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +        names.push(name);
Formatting issue

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    let lineName = null;
Why have you declared lineName here? I do not see usages apart from inside forEach

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    let stationNames = data.stationNames.concat(),
Please do not use single let when you declare variables. Use separate let for each declaration

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +            lineName = names.shift();
Why don't constract SubwayLine here?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    lines = data.lineNames.concat(),
Why do you do concat?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    for (let i = 0; i < stationNames.length; i++) {
What do you do here?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +function createLine(subwayName, stations) {
why do you use subwayName variable name if it is subwayLineName?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +function createStation(name) {
why do you need this function? it is easier just to call new Station(name)

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/startApp.js
> +const localStorageKey = 'data';
localStorageKey of what? such constants should contain information about what they are key for

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/startApp.js
> +    let file = e.target.files[0];
once again why let here if you do not change file reference?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/startApp.js
> +    let storageObj = JSON.stringify(currentSubway);
why let here if you do not change object reference?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/startApp.js
> +
unnecessary line

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/startApp.js
> +
two unnecessary lines. only one trailing line is acceptable

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    let currentStations = stations.concat();
Why do you do concat?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +function createLine(subwayName, stations) {
Why do you need this function?

2019-03-21 08:44 UTC, AndreiShenets commented on src/js/Parser.js
> +    for (let i = 0; i < lines.length; i++) {
Please explaing what is going on in this function...

2019-03-21 13:42 UTC, AndreiShenets requested changes

2019-03-21 13:42 UTC, AndreiShenets commented on src/js/Parser.js
> +			names = [];
Tabs, forSPACE(, names not exist

2019-03-21 13:42 UTC, AndreiShenets commented on src/js/Parser.js
> +    let currentData = data;
you do not need to store data to local variable you can just pass it to you function. after thatyou even do not need convertToSubway function you can move it's content to parse function

2019-03-21 13:42 UTC, AndreiShenets commented on src/js/Parser.js
> +    data = data.split('\n').map(name => name.trim());
I would add one empty line above and place each chain method to separate line

2019-03-21 13:42 UTC, AndreiShenets commented on src/js/Parser.js
> +            stationNames = stationNames.concat(allNames);
Why do you do concat? it seems that you do not need stationNames variable at all. Let's discuss the logic again

2019-03-21 15:37 UTC, AndreiShenets requested changes

2019-03-21 15:37 UTC, AndreiShenets commented on src/js/Parser.js
> +            .split('\n')
One tab shift

2019-03-22 10:16 UTC, AndreiShenets requested changes

2019-03-22 10:16 UTC, AndreiShenets commented on src/js/Parser.js
> +                stationNames[name] = new Station(name);
If name already exists you recreate object...

2019-03-22 10:16 UTC, AndreiShenets commented on src/js/Parser.js
> +            result[lineName] = allNames;
The issue above not allow you set stations here

2019-03-22 10:16 UTC, AndreiShenets commented on src/js/Parser.js
> +        stations = result[key].map(name => stationNames[name]);
The issue above force you to do this mapping

2019-03-25 06:33 UTC, AndreiShenets approved these changes

2019-03-25 06:33 UTC, merged